version: '3'
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETARCH=arm
    ports:
      - "8000:8000"
    environment:
      DOCKER_BUILDKIT: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app